# Generated by Django 3.0.6 on 2020-05-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('breed_id', models.AutoField(primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=100, unique=True)),
                ('image', models.CharField(max_length=300)),
                ('sizes', models.CharField(max_length=100)),
                ('fur_type', models.CharField(max_length=20)),
                ('ear_type', models.CharField(choices=[('—', 'Unknown'), ('Erect', 'Erect'), ('Lop', 'Lop')], default='Unknown', max_length=7)),
                ('colors', models.CharField(max_length=100)),
                ('ARBA_recognised', models.CharField(choices=[('—', 'Unknown'), ('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('BRC_recognised', models.CharField(choices=[('—', 'Unknown'), ('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('origins', models.CharField(max_length=100)),
            ],
        ),
    ]
