# Generated by Django 3.0.6 on 2020-05-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breedapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='breed',
            new_name='name',
        ),
    ]
