openapi: 3.0.2
info:
  title: 'Rabbit Breeds Api'
  version: ''
paths:
  /breeds/:
    get:
      operationId: listBreeds
      description: ''
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                  previous:
                    type: string
                    nullable: true
                  results:
                    type: array
                    items:
                      properties:
                        breed_id:
                          type: integer
                          readOnly: true
                        name:
                          type: string
                          maxLength: 100
                        image:
                          type: string
                          maxLength: 300
                        sizes:
                          type: string
                          maxLength: 100
                        fur_type:
                          type: string
                          maxLength: 20
                        ear_type:
                          enum:
                          - "\u2014"
                          - Erect
                          - Lop
                        colors:
                          type: string
                          maxLength: 100
                        ARBA_recognised:
                          enum:
                          - "\u2014"
                          - 'Yes'
                          - 'No'
                        BRC_recognised:
                          enum:
                          - "\u2014"
                          - 'Yes'
                          - 'No'
                        origins:
                          type: string
                          maxLength: 100
                      required:
                      - name
                      - sizes
                      - fur_type
                      - colors
                      - ARBA_recognised
                      - BRC_recognised
                      - origins
          description: ''
  /breeds/{breed_id}/:
    get:
      operationId: retrieveBreed
      description: ''
      parameters:
      - name: breed_id
        in: path
        required: true
        description: A unique integer value identifying this breed.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  breed_id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    maxLength: 100
                  image:
                    type: string
                    maxLength: 300
                  sizes:
                    type: string
                    maxLength: 100
                  fur_type:
                    type: string
                    maxLength: 20
                  ear_type:
                    enum:
                    - "\u2014"
                    - Erect
                    - Lop
                  colors:
                    type: string
                    maxLength: 100
                  ARBA_recognised:
                    enum:
                    - "\u2014"
                    - 'Yes'
                    - 'No'
                  BRC_recognised:
                    enum:
                    - "\u2014"
                    - 'Yes'
                    - 'No'
                  origins:
                    type: string
                    maxLength: 100
                required:
                - name
                - sizes
                - fur_type
                - colors
                - ARBA_recognised
                - BRC_recognised
                - origins
          description: ''
  /breeds-with-images/:
    get:
      operationId: listBreedsWithImagesViewSets
      description: 'Return only breeds with images.'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
  /random/:
    get:
      operationId: listBreeds
      description: 'Return random breed.'
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                  previous:
                    type: string
                    nullable: true
                  results:
                    type: array
                    items:
                      properties:
                        breed_id:
                          type: integer
                          readOnly: true
                        name:
                          type: string
                          maxLength: 100
                        image:
                          type: string
                          maxLength: 300
                        sizes:
                          type: string
                          maxLength: 100
                        fur_type:
                          type: string
                          maxLength: 20
                        ear_type:
                          enum:
                          - "\u2014"
                          - Erect
                          - Lop
                        colors:
                          type: string
                          maxLength: 100
                        ARBA_recognised:
                          enum:
                          - "\u2014"
                          - 'Yes'
                          - 'No'
                        BRC_recognised:
                          enum:
                          - "\u2014"
                          - 'Yes'
                          - 'No'
                        origins:
                          type: string
                          maxLength: 100
                      required:
                      - name
                      - sizes
                      - fur_type
                      - colors
                      - ARBA_recognised
                      - BRC_recognised
                      - origins
          description: ''
